apiVersion: apps/v1
kind: Deployment
metadata:
  name: es02
  namespace: default
  labels:
    application: logging
    component: es02
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: es02
  template:
    metadata:
      labels:
        application: logging
        component: es02
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es02
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MASTER_DISCOVERY_HOST
          value: "es-master"
        - name: ES_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
