apiVersion: v1
kind: Service
metadata:
  name: es02
  namespace: default
  labels:
    application: logging
    component: es02
spec:
  ports:
  - port: 9200
    name: http-elk
  selector:
    component: es02
