apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: default
  labels:
    application: logging
    component: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: http
  selector:
    component: kibana
