apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
  namespace: default
  labels:
    application: logging
    component: logstash
spec:
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP
    name: http
  selector:
    component: logstash
