apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: "8090"
  name: app-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30007 #
