apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: host-ingress
spec:
 rules:
  - host: bikash.devops.com
    http:
     paths:
     - backend:
        serviceName: app-service
        servicePort: 8090
