apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-pv-volume
  labels:
    type: local
spec:
  storageClassName: myapp
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
